name: parallel
channels:
  - conda-forge
  - defaults
dependencies:
  - python =3.6
  - bokeh
  - cloudpickle
  - dask
  - distributed
  - joblib
  - jupyter
  - jupyterlab
  - matplotlib
  - pandas
  - pandas-datareader
  - pytables
  - scikit-learn
  - snakeviz
  - ujson
  - gcsfs
  - ipywidgets
